# Generated by Django 4.2.1 on 2023-05-15 09:25

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("bmsApp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubscriptionPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("number_of_users", models.PositiveIntegerField()),
                (
                    "modules",
                    models.CharField(
                        choices=[
                            ("payroll", "PayRoll"),
                            ("leave", "Leave"),
                            ("appraisal", "Appraisal"),
                            ("attendance", "Attendance"),
                        ],
                        max_length=10,
                    ),
                ),
                ("price", models.PositiveBigIntegerField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="client",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="client",
            name="modified_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("due", "Due"), ("paid", "Paid")], max_length=10
                    ),
                ),
                (
                    "model",
                    models.CharField(
                        choices=[
                            ("1 month", "One Months"),
                            ("3 months", "Three Months"),
                            ("6 months", "Six Months"),
                            ("12 months", "Twelve Months"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "client",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="bmsApp.client"
                    ),
                ),
                (
                    "subscription_plan",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bmsApp.subscriptionplan",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Metrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "ram_usage",
                    models.FloatField(
                        max_length=200,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "hard_disk_usage",
                    models.FloatField(
                        max_length=200,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("number_of_users", models.PositiveIntegerField()),
                ("number_of_organizations", models.PositiveIntegerField()),
                (
                    "client",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="bmsApp.client"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
