# Generated by Django 4.2.1 on 2023-05-18 09:13

import bmsApp.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmsApp', '0003_history_alter_client_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(max_length=254, validators=[bmsApp.validators.validate_email]),
        ),
    ]
